name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install  # Adjust if you have specific dependencies, or skip if not needed

      - name: Prepare files for deployment
        run: |
          mkdir -p public
          cp -r Customer/HTML/* public/
          cp -r Customer/CSS public/CSS
          cp -r Customer/JS public/JS
          cp -r Customer/images public/images
          ls -la public  # List files in public directory for debugging

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --branch gh-pages https://github.com/${{ github.repository }} public || echo "gh-pages branch does not exist, creating a new one"
          cp -r Customer/HTML/* public/
          cd public
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push
